#
#	MIPS Release
#
PLATFORM_OUTDIR=MIPSRel
PLATFORM_INTDIR=MIPSRel
PLATFORM_CPP=clmips.exe
PLATFORM_CPP_PROJ=/D "MIPS" /D "_MIPS_" /D "NDEBUG" $(CFLAGS) /Oxs 
PLATFORM_LINK32_FLAGS=/subsystem:$(CESubsystem) /MACHINE:MIPS 
PLATFORM_LINK32_DLL_FLAGS=/base:"0x00100000" /entry:"_DllMainCRTStartup" $(PLATFORM_LINK32_FLAGS)
PLATFORM_RSCFLAGS=/d "MIPS" /d "_MIPS_" /d "NDEBUG"
