#
#	MIPS Debug
#
PLATFORM_OUTDIR=MIPSDbg
PLATFORM_INTDIR=MIPSDbg
#PLATFORM_DLL_SUFFIX=_d
PLATFORM_CPP=clmips.exe
PLATFORM_CPP_PROJ=/D "MIPS" /D "_MIPS_" $(CFLAGS_DEBUG) 
PLATFORM_LINK32_FLAGS=/debug /subsystem:$(CESubsystem) /MACHINE:MIPS 
PLATFORM_LINK32_DLL_FLAGS=/base:"0x00100000" /entry:"_DllMainCRTStartup" $(PLATFORM_LINK32_FLAGS)
PLATFORM_RSCFLAGS=/d "MIPS" /d "_MIPS_" /d "DEBUG"
