#
#	SH3 Debug
#
PLATFORM_OUTDIR=SH3Dbg
PLATFORM_INTDIR=SH3Dbg
#PLATFORM_DLL_SUFFIX=_d
PLATFORM_CPP=shcl.exe
PLATFORM_CPP_PROJ=/D "SHx" /D "SH3" /D "_SH3_" $(CFLAGS_DEBUG) 
PLATFORM_LINK32_FLAGS=/debug /subsystem:$(CESubsystem) /MACHINE:SH3 
PLATFORM_LINK32_DLL_FLAGS=/base:"0x00100000" /entry:"_DllMainCRTStartup" $(PLATFORM_LINK32_FLAGS)
PLATFORM_RSCFLAGS=/d "SHx" /d "SH3" /d "_SH3_" /d "DEBUG"
