#
#	SH3 Release
#
PLATFORM_OUTDIR=SH3Rel
PLATFORM_INTDIR=SH3Rel
PLATFORM_CPP=shcl.exe
PLATFORM_CPP_PROJ=/D "SHx" /D "SH3" /D "_SH3_" /D "NDEBUG" $(CFLAGS) /Oxs 
PLATFORM_LINK32_FLAGS=/subsystem:$(CESubsystem) /MACHINE:SH3 
PLATFORM_LINK32_DLL_FLAGS=/base:"0x00100000" /entry:"_DllMainCRTStartup" $(PLATFORM_LINK32_FLAGS)
PLATFORM_RSCFLAGS=/d "SHx" /d "SH3" /d "_SH3_" /d "NDEBUG"
