#
#	SH4 Debug
#
PLATFORM_OUTDIR=SH4Dbg
PLATFORM_INTDIR=SH4Dbg
#PLATFORM_DLL_SUFFIX=_d
PLATFORM_CPP=shcl.exe
PLATFORM_CPP_PROJ=/D "SHx" /D "SH4" /D "_SH4_" $(CFLAGS_DEBUG) /Qsh4 
PLATFORM_LINK32_FLAGS=/debug /subsystem:$(CESubsystem) /MACHINE:SH4 
PLATFORM_LINK32_DLL_FLAGS=/base:"0x00100000" /entry:"_DllMainCRTStartup" $(PLATFORM_LINK32_FLAGS)
PLATFORM_RSCFLAGS=/d "SHx" /d "SH4" /d "_SH4_" /d "DEBUG"
