#
#	SH4 Release
#
PLATFORM_OUTDIR=SH4Rel
PLATFORM_INTDIR=SH4Rel
PLATFORM_CPP=shcl.exe
PLATFORM_CPP_PROJ=/D "SHx" /D "SH4" /D "_SH4_" /D "NDEBUG" $(CFLAGS) /Qsh4 /Oxs 
PLATFORM_LINK32_FLAGS=/subsystem:$(CESubsystem) /MACHINE:SH4 
PLATFORM_LINK32_DLL_FLAGS=/base:"0x00100000" /entry:"_DllMainCRTStartup" $(PLATFORM_LINK32_FLAGS)
PLATFORM_RSCFLAGS=/d "SHx" /d "SH4" /d "_SH4_" /d "NDEBUG"
