#
#	X86 Emulator Debug
#
PLATFORM_OUTDIR=X86EMDbg
PLATFORM_INTDIR=X86EMDbg
#PLATFORM_DLL_SUFFIX=_d
PLATFORM_CPP=cl.exe
PLATFORM_CPP_PROJ=/Od /D "_DEBUG" /D "i486" /D "_X86_" /D "x86" $(CFLAGS_DEBUG) $(CFLAGS) /FR"$(INTDIR)\\" /Gz 
PLATFORM_LINK32_FLAGS=/debug /windowsce:emulation /MACHINE:IX86
PLATFORM_LINK32_DLL_FLAGS=$(PLATFORM_LINK32_FLAGS)
PLATFORM_RSCFLAGS=/d "_X86_" /d "x86" /d "i486" /d "DEBUG"
